# Generated by Django 4.0.2 on 2022-03-15 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploreimage',
            name='explore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore', to='explore.explore'),
        ),
    ]
