# Generated by Django 4.0.2 on 2022-03-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=35)),
                ('website', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('please_note', models.TextField()),
                ('twitter_url', models.CharField(max_length=355)),
                ('instagram_url', models.CharField(max_length=355)),
                ('facebook_url', models.CharField(max_length=355)),
                ('type_model', models.CharField(choices=[('kosher_grocery', 'kosher_grocery'), ('some_kosher_items', 'some_kosher_items'), ('kosher_bakery', 'kosher_bakery')], max_length=48)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=35)),
                ('website', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('please_note', models.TextField()),
                ('twitter_url', models.CharField(max_length=355)),
                ('instagram_url', models.CharField(max_length=355)),
                ('facebook_url', models.CharField(max_length=355)),
                ('type_model', models.CharField(choices=[('dairy', 'dairy'), ('pareve', 'pareve'), ('meat', 'meat')], max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItHas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=35)),
                ('website', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('please_note', models.TextField()),
                ('twitter_url', models.CharField(max_length=355)),
                ('instagram_url', models.CharField(max_length=355)),
                ('facebook_url', models.CharField(max_length=355)),
                ('type_model', models.CharField(choices=[('dairy', 'dairy'), ('pareve', 'pareve'), ('meat', 'meat')], max_length=25)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.foodtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=35)),
                ('website', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('please_note', models.TextField()),
                ('twitter_url', models.CharField(max_length=355)),
                ('instagram_url', models.CharField(max_length=355)),
                ('facebook_url', models.CharField(max_length=355)),
                ('type_model', models.CharField(choices=[('kosher_grocery', 'kosher_grocery'), ('some_kosher_items', 'some_kosher_items'), ('kosher_bakery', 'kosher_bakery')], max_length=48)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.foodtype')),
                ('service_options', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.serviceoption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TakeOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=35)),
                ('website', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10)),
                ('please_note', models.TextField()),
                ('twitter_url', models.CharField(max_length=355)),
                ('instagram_url', models.CharField(max_length=355)),
                ('facebook_url', models.CharField(max_length=355)),
                ('type_model', models.CharField(choices=[('dairy', 'dairy'), ('pareve', 'pareve'), ('meat', 'meat')], max_length=25)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.foodtype')),
                ('service_options', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.serviceoption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('week_day', models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], max_length=25)),
                ('is_holiday', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TakeOutWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('take_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.takeout')),
                ('working_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.workinghours')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TakeOutServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('service_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.serviceoption')),
                ('take_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.takeout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TakeOutOrderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('take_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.takeout')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.websitelink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TakeOutMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.menu')),
                ('take_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.takeout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TakeOutMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('take_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.takeout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TakeOutMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.takeoutmenu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TakeOutHas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('it_has', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.ithas')),
                ('take_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.takeout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TakeOutFoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodtype')),
                ('take_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.takeout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperMarketWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.supermarket')),
                ('working_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.workinghours')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperMarketServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('service_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.serviceoption')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.supermarket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperMarketOrderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.supermarket')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.websitelink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperMarketMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.menu')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.supermarket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperMarketMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.supermarket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperMarketMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.supermarketmenu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperMarketHas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('it_has', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.ithas')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.supermarket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperMarketFoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodtype')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.supermarket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.restaurant')),
                ('working_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.workinghours')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.restaurant')),
                ('service_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.serviceoption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantReserveSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.restaurant')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.websitelink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantOrderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.restaurant')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.websitelink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.restaurantmenu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantHas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('it_has', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.ithas')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('good_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.goodfor')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantFoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodtype')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.serviceoption'),
        ),
        migrations.AddField(
            model_name='meal',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.menu'),
        ),
        migrations.AddField(
            model_name='meal',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='file.file'),
        ),
        migrations.CreateModel(
            name='FoodServiceWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodservice')),
                ('working_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.workinghours')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodServiceReserveSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodservice')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.websitelink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodServiceOrderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodservice')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.websitelink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodservice')),
                ('service_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.serviceoption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodServiceMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodservice')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodServiceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodServiceMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodservicemenu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodServiceHas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodservice')),
                ('it_has', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.ithas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodServiceFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodservice')),
                ('good_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.goodfor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodServiceFoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodservice')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='foodservice',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.foodtype'),
        ),
        migrations.AddField(
            model_name='foodservice',
            name='service_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.serviceoption'),
        ),
        migrations.CreateModel(
            name='BakeryWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.bakery')),
                ('working_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.workinghours')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakeryServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.bakery')),
                ('service_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.serviceoption')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakeryOrderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.bakery')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.websitelink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakeryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.bakery')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakeryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.bakery')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakeryMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.bakerymenu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakeryHas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.bakery')),
                ('it_has', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.ithas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakeryFoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.bakery')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bakery',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.foodtype'),
        ),
        migrations.AddField(
            model_name='bakery',
            name='service_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.serviceoption'),
        ),
    ]
