# Generated by Django 4.0.2 on 2022-03-15 09:43

# Django
from django.db import migrations

# Defaults
FOOD_TYPES = ['Breakfast', 'Lunch', 'Dinner', 'Shabbos food', 'Groceries', 'Bakeries']
SERVICE_OPTIONS = ['Dine-in', 'Takeout', 'Delivery', 'Curbside pickup', 'Catering']
IT_HAS = ['Sandwich bar', 'Salad bar', 'Kids menu', 'Free Parking', 'Free wifi']
GOOD_FOR = ['Family', 'Kids', 'Outing', 'Dates']


def default_food_types(apps, schema_editor):
    FoodType = apps.get_model("food_dining", "FoodType")
    db_alias = schema_editor.connection.alias
    FoodType.objects.using(db_alias).bulk_create([
        FoodType(name=_type) for _type in FOOD_TYPES
    ])


def default_service_options(apps, schema_editor):
    ServiceOption = apps.get_model("food_dining", "ServiceOption")
    db_alias = schema_editor.connection.alias
    ServiceOption.objects.using(db_alias).bulk_create([
        ServiceOption(name=option) for option in SERVICE_OPTIONS
    ])


def default_it_has(apps, schema_editor):
    ItHas = apps.get_model("food_dining", "ItHas")
    db_alias = schema_editor.connection.alias
    ItHas.objects.using(db_alias).bulk_create([
        ItHas(name=name) for name in IT_HAS
    ])


def default_good_for(apps, schema_editor):
    GoodFor = apps.get_model("food_dining", "GoodFor")
    db_alias = schema_editor.connection.alias
    GoodFor.objects.using(db_alias).bulk_create([
        GoodFor(name=name) for name in GOOD_FOR
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('food_dining', '0004_websitelink_logo'),
    ]

    operations = [
        migrations.RunPython(default_food_types),
        migrations.RunPython(default_service_options),
        migrations.RunPython(default_it_has),
        migrations.RunPython(default_good_for),
    ]
