# Generated by Django 4.0.2 on 2022-03-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_dining', '0005_auto_20220315_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitelink',
            old_name='logo',
            new_name='file',
        ),
    ]
