# Generated by Django 4.0.2 on 2022-03-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_dining', '0006_rename_logo_websitelink_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='foodservice',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='foodservice',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='takeout',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='takeout',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
    ]
