# Generated by Django 4.0.2 on 2022-03-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_dining', '0009_bakery_creator_foodservice_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
