# Generated by Django 4.0.2 on 2022-03-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_dining', '0010_alter_workinghours_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=555)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReserveSiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=555)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bakeryordersite',
            name='website',
        ),
        migrations.RemoveField(
            model_name='foodserviceordersite',
            name='website',
        ),
        migrations.RemoveField(
            model_name='foodservicereservesite',
            name='website',
        ),
        migrations.RemoveField(
            model_name='restaurantordersite',
            name='website',
        ),
        migrations.RemoveField(
            model_name='restaurantreservesite',
            name='website',
        ),
        migrations.RemoveField(
            model_name='supermarketordersite',
            name='website',
        ),
        migrations.RemoveField(
            model_name='takeoutordersite',
            name='website',
        ),
        migrations.DeleteModel(
            name='WebsiteLink',
        ),
        migrations.AddField(
            model_name='bakeryordersite',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_dining.ordersitelink'),
        ),
        migrations.AddField(
            model_name='foodserviceordersite',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_dining.ordersitelink'),
        ),
        migrations.AddField(
            model_name='foodservicereservesite',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_dining.reservesitelink'),
        ),
        migrations.AddField(
            model_name='restaurantordersite',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_dining.ordersitelink'),
        ),
        migrations.AddField(
            model_name='restaurantreservesite',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_dining.reservesitelink'),
        ),
        migrations.AddField(
            model_name='supermarketordersite',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_dining.ordersitelink'),
        ),
        migrations.AddField(
            model_name='takeoutordersite',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_dining.ordersitelink'),
        ),
    ]
