# Generated by Django 4.0.2 on 2022-03-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_is_main_file_ordering'),
        ('food_dining', '0012_remove_bakerymenu_bakery_remove_bakerymenu_menu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeOutMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.takeout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TakeOutMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.takeoutmenu')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='file.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperMarketMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.supermarket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperMarketMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.supermarketmenu')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='file.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.restaurant')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='file.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodServiceMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('food_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.foodservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodServiceMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.foodservicemenu')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='file.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakeryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.bakery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakeryMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_dining.bakerymenu')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='file.file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
