# Generated by Django 4.0.2 on 2022-03-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_dining', '0015_alter_restaurantmeal_menu'),
        ('food_dining', '0016_alter_bakerymeal_menu_alter_foodservicemeal_menu_and_more'),
    ]

    operations = [
    ]
