# Generated by Django 4.0.2 on 2022-03-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_dining', '0017_merge_20220328_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmeal',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_dining.restaurantmenu'),
        ),
    ]
