# Generated by Django 4.0.2 on 2022-02-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_network',
            field=models.CharField(default='local', max_length=35),
        ),
    ]
