# Generated by Django 4.0.2 on 2022-03-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='ordering',
            field=models.IntegerField(default=1),
        ),
    ]
